name: Rclone Sync

on:
  schedule:
    - cron: '0 19 * * 2'
  workflow_dispatch:

jobs:
  rclone_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
      - name: Sync with Rclone
        run: |
          rclone sync main:Docs backup:Docs --verbose | tee rclone_log.txt
          echo "Rclone sync completed!"
      - name: Upload log artifact
        uses: actions/upload-artifact@v3
        with:
          name: rclone-log
          path: rclone_log.txt
        
  send_email:
    runs-on: ubuntu-latest
    needs: rclone_sync
    steps:
      - name: Download log artifact
        uses: actions/download-artifact@v3
        with:
          name: rclone-log
          path: .
      - name: Send mail
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          ignore_cert: true
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Backup results
          to: nhloc08@gmail.com
          from: Nguyen Hoang Loc
          body: |
            Backup process completed.
            Logs:
            $(cat rclone_log.txt)
