name: Rclone Sync

on:
  schedule:
    - cron: '0 19 * * 2'
  workflow_dispatch:

jobs:
  rclone_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}          
      - run: |
          rclone sync main_viethoangprobie: backup_sinhvien: \
            --log-file=rclone-log.txt \
            --log-level INFO
      - name: File update status
        id: analyze_log
        run: |
          echo "Rclone Backup Report" > report.txt
          echo " " >> report.txt
          echo "Files successfully synced:" >> report.txt
          grep "INFO  :" rclone-log.txt | grep "Copied" >> report.txt || echo "No files synced." >> report.txt
          echo "" >> report.txt
          echo "Errors during sync:" >> report.txt
          grep "ERROR :" rclone-log.txt >> report.txt || echo "No errors found." >> report.txt
      
  send_email:
    runs-on: ubuntu-latest
    needs: rclone_sync
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send mail
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          ignore_cert: true
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Backup results
          to: hoangvuive250106@gmail.com
          from: Nguyen Hoang Loc
          body: |
            Backup process completed.
            See attached log for details.
          attachments: report.txt
