name: Rclone Sync

on:
  schedule:
    - cron: '0 19 * * 2'
  workflow_dispatch:

jobs:
  rclone_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - name: Run Rclone and generate report
        run: |
          LOG_CONTENT=""
          LOG_CONTENT+="Rclone Backup Report\n\n"
          LOG_CONTENT+="Files successfully synced:\n"
          SYNCED_FILES=$(grep "INFO  :" rclone-log.txt | grep "Copied" || echo "No files synced.")
          LOG_CONTENT+="$SYNCED_FILES\n\n"
          LOG_CONTENT+="Errors during sync:\n"
          ERRORS=$(grep "ERROR :" rclone-log.txt || echo "No errors found.")
          LOG_CONTENT+="$ERRORS"
          echo "RCLONE_REPORT<<EOF" >> $GITHUB_ENV
          echo -e "$LOG_CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Debug Rclone Report
        run: echo "${{ env.RCLONE_REPORT }}"
        
  send_email:
    runs-on: ubuntu-latest
    needs: rclone_sync
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          ignore_cert: true
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Backup results
          to: nhloc08@gmail.com
          from: Nguyen Hoang Loc
          body: |
            ${{ env.RCLONE_REPORT }}
