name: Send Email on Success

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send mail
        uses: dawidd6/action-send-mail@v4
        with:
          # Specify connection via URL (replaces server_address, server_port, secure, username, password)
          connection_url: ${{ secrets.MAIL_CONNECTION }}

          # Required mail server address if not connection_url:
          server_address: smtp.gmail.com

          # Server port for SSL (465)
          server_port: 465
          ignore_cert: true
          secure: true

          # Optional mail server username (use Gmail address)
          username: ${{ secrets.MAIL_USERNAME }}

          # Optional mail server password (use App Password)
          password: ${{ secrets.MAIL_PASSWORD }}

          # Required mail subject
          subject: "Github Actions job result"

          # Required recipients' addresses
          to: nhloc08@gmail.com

          # Required sender full name (address can be skipped)
          from: Nguyen Hoang Loc

          # Optional plain body
          body: "Build job of ${{ github.repository }} completed successfully!"
