name: Send Email on Success

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send mail
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          ignore_cert: true
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Github Actions job result"

          # Required recipients' addresses
          to: nhloc08@gmail.com

          # Required sender full name (address can be skipped)
          from: Nguyen Hoang Loc

          # Optional plain body
          body: "Build job of ${{ github.repository }} completed successfully!"
